version: "3"

services:
  velero:
    image: velero-dashboard
    environment:
      DEBUG: "true"
      KUBECONFIG: "/tmp/.kube/config"
    volumes:
      - ../config:/tmp/.kube/config:ro
      - ../../src:/app:ro
      - /tmp/minikube/:/tmp/minikube/:ro
    entrypoint: python /app/run.py
    ports:
      - 8080:8080
#    network_mode: bridge
